//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlocoX.SefazSC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ConfigurationName="SefazSC.BlocoXSoap")]
    public interface BlocoXSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pXmlCompactado no namespace http://webservices.sef.sc.gov.br/wsDfeSiv/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/TransmitirArquivo", ReplyAction="*")]
        BlocoX.SefazSC.TransmitirArquivoResponse TransmitirArquivo(BlocoX.SefazSC.TransmitirArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/TransmitirArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<BlocoX.SefazSC.TransmitirArquivoResponse> TransmitirArquivoAsync(BlocoX.SefazSC.TransmitirArquivoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pXml no namespace http://webservices.sef.sc.gov.br/wsDfeSiv/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarProcessamentoArquivo", ReplyAction="*")]
        BlocoX.SefazSC.ConsultarProcessamentoArquivoResponse ConsultarProcessamentoArquivo(BlocoX.SefazSC.ConsultarProcessamentoArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarProcessamentoArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarProcessamentoArquivoResponse> ConsultarProcessamentoArquivoAsync(BlocoX.SefazSC.ConsultarProcessamentoArquivoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pXml no namespace http://webservices.sef.sc.gov.br/wsDfeSiv/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/DownloadArquivo", ReplyAction="*")]
        BlocoX.SefazSC.DownloadArquivoResponse DownloadArquivo(BlocoX.SefazSC.DownloadArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/DownloadArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<BlocoX.SefazSC.DownloadArquivoResponse> DownloadArquivoAsync(BlocoX.SefazSC.DownloadArquivoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pXml no namespace http://webservices.sef.sc.gov.br/wsDfeSiv/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/CancelarArquivo", ReplyAction="*")]
        BlocoX.SefazSC.CancelarArquivoResponse CancelarArquivo(BlocoX.SefazSC.CancelarArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/CancelarArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<BlocoX.SefazSC.CancelarArquivoResponse> CancelarArquivoAsync(BlocoX.SefazSC.CancelarArquivoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pXml no namespace http://webservices.sef.sc.gov.br/wsDfeSiv/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ReprocessarArquivo", ReplyAction="*")]
        BlocoX.SefazSC.ReprocessarArquivoResponse ReprocessarArquivo(BlocoX.SefazSC.ReprocessarArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ReprocessarArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ReprocessarArquivoResponse> ReprocessarArquivoAsync(BlocoX.SefazSC.ReprocessarArquivoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pXml no namespace http://webservices.sef.sc.gov.br/wsDfeSiv/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarPendenciasDesenvolvedorPafEcf", ReplyAction="*")]
        BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfResponse ConsultarPendenciasDesenvolvedorPafEcf(BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarPendenciasDesenvolvedorPafEcf", ReplyAction="*")]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfResponse> ConsultarPendenciasDesenvolvedorPafEcfAsync(BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pXml no namespace http://webservices.sef.sc.gov.br/wsDfeSiv/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarPendenciasContribuinte", ReplyAction="*")]
        BlocoX.SefazSC.ConsultarPendenciasContribuinteResponse ConsultarPendenciasContribuinte(BlocoX.SefazSC.ConsultarPendenciasContribuinteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarPendenciasContribuinte", ReplyAction="*")]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarPendenciasContribuinteResponse> ConsultarPendenciasContribuinteAsync(BlocoX.SefazSC.ConsultarPendenciasContribuinteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pXml no namespace http://webservices.sef.sc.gov.br/wsDfeSiv/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ListarArquivos", ReplyAction="*")]
        BlocoX.SefazSC.ListarArquivosResponse ListarArquivos(BlocoX.SefazSC.ListarArquivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ListarArquivos", ReplyAction="*")]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ListarArquivosResponse> ListarArquivosAsync(BlocoX.SefazSC.ListarArquivosRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento pXml no namespace http://webservices.sef.sc.gov.br/wsDfeSiv/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarHistoricoArquivo", ReplyAction="*")]
        BlocoX.SefazSC.ConsultarHistoricoArquivoResponse ConsultarHistoricoArquivo(BlocoX.SefazSC.ConsultarHistoricoArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarHistoricoArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarHistoricoArquivoResponse> ConsultarHistoricoArquivoAsync(BlocoX.SefazSC.ConsultarHistoricoArquivoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ConsultarStatusMetodosBlocoXResult no namespace http://webservices.sef.sc.gov.br/wsDfeSiv/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarStatusMetodosBlocoX", ReplyAction="*")]
        BlocoX.SefazSC.ConsultarStatusMetodosBlocoXResponse ConsultarStatusMetodosBlocoX(BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarStatusMetodosBlocoX", ReplyAction="*")]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarStatusMetodosBlocoXResponse> ConsultarStatusMetodosBlocoXAsync(BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransmitirArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransmitirArquivo", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.TransmitirArquivoRequestBody Body;
        
        public TransmitirArquivoRequest() {
        }
        
        public TransmitirArquivoRequest(BlocoX.SefazSC.TransmitirArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class TransmitirArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] pXmlCompactado;
        
        public TransmitirArquivoRequestBody() {
        }
        
        public TransmitirArquivoRequestBody(byte[] pXmlCompactado) {
            this.pXmlCompactado = pXmlCompactado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransmitirArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransmitirArquivoResponse", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.TransmitirArquivoResponseBody Body;
        
        public TransmitirArquivoResponse() {
        }
        
        public TransmitirArquivoResponse(BlocoX.SefazSC.TransmitirArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class TransmitirArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TransmitirArquivoResult;
        
        public TransmitirArquivoResponseBody() {
        }
        
        public TransmitirArquivoResponseBody(string TransmitirArquivoResult) {
            this.TransmitirArquivoResult = TransmitirArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProcessamentoArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProcessamentoArquivo", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ConsultarProcessamentoArquivoRequestBody Body;
        
        public ConsultarProcessamentoArquivoRequest() {
        }
        
        public ConsultarProcessamentoArquivoRequest(BlocoX.SefazSC.ConsultarProcessamentoArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ConsultarProcessamentoArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pXml;
        
        public ConsultarProcessamentoArquivoRequestBody() {
        }
        
        public ConsultarProcessamentoArquivoRequestBody(string pXml) {
            this.pXml = pXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProcessamentoArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProcessamentoArquivoResponse", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ConsultarProcessamentoArquivoResponseBody Body;
        
        public ConsultarProcessamentoArquivoResponse() {
        }
        
        public ConsultarProcessamentoArquivoResponse(BlocoX.SefazSC.ConsultarProcessamentoArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ConsultarProcessamentoArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarProcessamentoArquivoResult;
        
        public ConsultarProcessamentoArquivoResponseBody() {
        }
        
        public ConsultarProcessamentoArquivoResponseBody(string ConsultarProcessamentoArquivoResult) {
            this.ConsultarProcessamentoArquivoResult = ConsultarProcessamentoArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadArquivo", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.DownloadArquivoRequestBody Body;
        
        public DownloadArquivoRequest() {
        }
        
        public DownloadArquivoRequest(BlocoX.SefazSC.DownloadArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class DownloadArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pXml;
        
        public DownloadArquivoRequestBody() {
        }
        
        public DownloadArquivoRequestBody(string pXml) {
            this.pXml = pXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadArquivoResponse", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.DownloadArquivoResponseBody Body;
        
        public DownloadArquivoResponse() {
        }
        
        public DownloadArquivoResponse(BlocoX.SefazSC.DownloadArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class DownloadArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DownloadArquivoResult;
        
        public DownloadArquivoResponseBody() {
        }
        
        public DownloadArquivoResponseBody(string DownloadArquivoResult) {
            this.DownloadArquivoResult = DownloadArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarArquivo", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.CancelarArquivoRequestBody Body;
        
        public CancelarArquivoRequest() {
        }
        
        public CancelarArquivoRequest(BlocoX.SefazSC.CancelarArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class CancelarArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pXml;
        
        public CancelarArquivoRequestBody() {
        }
        
        public CancelarArquivoRequestBody(string pXml) {
            this.pXml = pXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarArquivoResponse", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.CancelarArquivoResponseBody Body;
        
        public CancelarArquivoResponse() {
        }
        
        public CancelarArquivoResponse(BlocoX.SefazSC.CancelarArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class CancelarArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancelarArquivoResult;
        
        public CancelarArquivoResponseBody() {
        }
        
        public CancelarArquivoResponseBody(string CancelarArquivoResult) {
            this.CancelarArquivoResult = CancelarArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReprocessarArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReprocessarArquivo", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ReprocessarArquivoRequestBody Body;
        
        public ReprocessarArquivoRequest() {
        }
        
        public ReprocessarArquivoRequest(BlocoX.SefazSC.ReprocessarArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ReprocessarArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pXml;
        
        public ReprocessarArquivoRequestBody() {
        }
        
        public ReprocessarArquivoRequestBody(string pXml) {
            this.pXml = pXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReprocessarArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReprocessarArquivoResponse", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ReprocessarArquivoResponseBody Body;
        
        public ReprocessarArquivoResponse() {
        }
        
        public ReprocessarArquivoResponse(BlocoX.SefazSC.ReprocessarArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ReprocessarArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReprocessarArquivoResult;
        
        public ReprocessarArquivoResponseBody() {
        }
        
        public ReprocessarArquivoResponseBody(string ReprocessarArquivoResult) {
            this.ReprocessarArquivoResult = ReprocessarArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPendenciasDesenvolvedorPafEcfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarPendenciasDesenvolvedorPafEcf", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequestBody Body;
        
        public ConsultarPendenciasDesenvolvedorPafEcfRequest() {
        }
        
        public ConsultarPendenciasDesenvolvedorPafEcfRequest(BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ConsultarPendenciasDesenvolvedorPafEcfRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pXml;
        
        public ConsultarPendenciasDesenvolvedorPafEcfRequestBody() {
        }
        
        public ConsultarPendenciasDesenvolvedorPafEcfRequestBody(string pXml) {
            this.pXml = pXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPendenciasDesenvolvedorPafEcfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarPendenciasDesenvolvedorPafEcfResponse", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfResponseBody Body;
        
        public ConsultarPendenciasDesenvolvedorPafEcfResponse() {
        }
        
        public ConsultarPendenciasDesenvolvedorPafEcfResponse(BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ConsultarPendenciasDesenvolvedorPafEcfResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarPendenciasDesenvolvedorPafEcfResult;
        
        public ConsultarPendenciasDesenvolvedorPafEcfResponseBody() {
        }
        
        public ConsultarPendenciasDesenvolvedorPafEcfResponseBody(string ConsultarPendenciasDesenvolvedorPafEcfResult) {
            this.ConsultarPendenciasDesenvolvedorPafEcfResult = ConsultarPendenciasDesenvolvedorPafEcfResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPendenciasContribuinteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarPendenciasContribuinte", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ConsultarPendenciasContribuinteRequestBody Body;
        
        public ConsultarPendenciasContribuinteRequest() {
        }
        
        public ConsultarPendenciasContribuinteRequest(BlocoX.SefazSC.ConsultarPendenciasContribuinteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ConsultarPendenciasContribuinteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pXml;
        
        public ConsultarPendenciasContribuinteRequestBody() {
        }
        
        public ConsultarPendenciasContribuinteRequestBody(string pXml) {
            this.pXml = pXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPendenciasContribuinteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarPendenciasContribuinteResponse", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ConsultarPendenciasContribuinteResponseBody Body;
        
        public ConsultarPendenciasContribuinteResponse() {
        }
        
        public ConsultarPendenciasContribuinteResponse(BlocoX.SefazSC.ConsultarPendenciasContribuinteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ConsultarPendenciasContribuinteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarPendenciasContribuinteResult;
        
        public ConsultarPendenciasContribuinteResponseBody() {
        }
        
        public ConsultarPendenciasContribuinteResponseBody(string ConsultarPendenciasContribuinteResult) {
            this.ConsultarPendenciasContribuinteResult = ConsultarPendenciasContribuinteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarArquivosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarArquivos", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ListarArquivosRequestBody Body;
        
        public ListarArquivosRequest() {
        }
        
        public ListarArquivosRequest(BlocoX.SefazSC.ListarArquivosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ListarArquivosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pXml;
        
        public ListarArquivosRequestBody() {
        }
        
        public ListarArquivosRequestBody(string pXml) {
            this.pXml = pXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarArquivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarArquivosResponse", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ListarArquivosResponseBody Body;
        
        public ListarArquivosResponse() {
        }
        
        public ListarArquivosResponse(BlocoX.SefazSC.ListarArquivosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ListarArquivosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListarArquivosResult;
        
        public ListarArquivosResponseBody() {
        }
        
        public ListarArquivosResponseBody(string ListarArquivosResult) {
            this.ListarArquivosResult = ListarArquivosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarHistoricoArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarHistoricoArquivo", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ConsultarHistoricoArquivoRequestBody Body;
        
        public ConsultarHistoricoArquivoRequest() {
        }
        
        public ConsultarHistoricoArquivoRequest(BlocoX.SefazSC.ConsultarHistoricoArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ConsultarHistoricoArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pXml;
        
        public ConsultarHistoricoArquivoRequestBody() {
        }
        
        public ConsultarHistoricoArquivoRequestBody(string pXml) {
            this.pXml = pXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarHistoricoArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarHistoricoArquivoResponse", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ConsultarHistoricoArquivoResponseBody Body;
        
        public ConsultarHistoricoArquivoResponse() {
        }
        
        public ConsultarHistoricoArquivoResponse(BlocoX.SefazSC.ConsultarHistoricoArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ConsultarHistoricoArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarHistoricoArquivoResult;
        
        public ConsultarHistoricoArquivoResponseBody() {
        }
        
        public ConsultarHistoricoArquivoResponseBody(string ConsultarHistoricoArquivoResult) {
            this.ConsultarHistoricoArquivoResult = ConsultarHistoricoArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarStatusMetodosBlocoXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarStatusMetodosBlocoX", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequestBody Body;
        
        public ConsultarStatusMetodosBlocoXRequest() {
        }
        
        public ConsultarStatusMetodosBlocoXRequest(BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarStatusMetodosBlocoXRequestBody {
        
        public ConsultarStatusMetodosBlocoXRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarStatusMetodosBlocoXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarStatusMetodosBlocoXResponse", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Order=0)]
        public BlocoX.SefazSC.ConsultarStatusMetodosBlocoXResponseBody Body;
        
        public ConsultarStatusMetodosBlocoXResponse() {
        }
        
        public ConsultarStatusMetodosBlocoXResponse(BlocoX.SefazSC.ConsultarStatusMetodosBlocoXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class ConsultarStatusMetodosBlocoXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarStatusMetodosBlocoXResult;
        
        public ConsultarStatusMetodosBlocoXResponseBody() {
        }
        
        public ConsultarStatusMetodosBlocoXResponseBody(string ConsultarStatusMetodosBlocoXResult) {
            this.ConsultarStatusMetodosBlocoXResult = ConsultarStatusMetodosBlocoXResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BlocoXSoapChannel : BlocoX.SefazSC.BlocoXSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlocoXSoapClient : System.ServiceModel.ClientBase<BlocoX.SefazSC.BlocoXSoap>, BlocoX.SefazSC.BlocoXSoap {
        
        public BlocoXSoapClient() {
        }
        
        public BlocoXSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlocoXSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlocoXSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlocoXSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlocoX.SefazSC.TransmitirArquivoResponse BlocoX.SefazSC.BlocoXSoap.TransmitirArquivo(BlocoX.SefazSC.TransmitirArquivoRequest request) {
            return base.Channel.TransmitirArquivo(request);
        }
        
        public string TransmitirArquivo(byte[] pXmlCompactado) {
            BlocoX.SefazSC.TransmitirArquivoRequest inValue = new BlocoX.SefazSC.TransmitirArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.TransmitirArquivoRequestBody();
            inValue.Body.pXmlCompactado = pXmlCompactado;
            BlocoX.SefazSC.TransmitirArquivoResponse retVal = ((BlocoX.SefazSC.BlocoXSoap)(this)).TransmitirArquivo(inValue);
            return retVal.Body.TransmitirArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlocoX.SefazSC.TransmitirArquivoResponse> BlocoX.SefazSC.BlocoXSoap.TransmitirArquivoAsync(BlocoX.SefazSC.TransmitirArquivoRequest request) {
            return base.Channel.TransmitirArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlocoX.SefazSC.TransmitirArquivoResponse> TransmitirArquivoAsync(byte[] pXmlCompactado) {
            BlocoX.SefazSC.TransmitirArquivoRequest inValue = new BlocoX.SefazSC.TransmitirArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.TransmitirArquivoRequestBody();
            inValue.Body.pXmlCompactado = pXmlCompactado;
            return ((BlocoX.SefazSC.BlocoXSoap)(this)).TransmitirArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlocoX.SefazSC.ConsultarProcessamentoArquivoResponse BlocoX.SefazSC.BlocoXSoap.ConsultarProcessamentoArquivo(BlocoX.SefazSC.ConsultarProcessamentoArquivoRequest request) {
            return base.Channel.ConsultarProcessamentoArquivo(request);
        }
        
        public string ConsultarProcessamentoArquivo(string pXml) {
            BlocoX.SefazSC.ConsultarProcessamentoArquivoRequest inValue = new BlocoX.SefazSC.ConsultarProcessamentoArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.ConsultarProcessamentoArquivoRequestBody();
            inValue.Body.pXml = pXml;
            BlocoX.SefazSC.ConsultarProcessamentoArquivoResponse retVal = ((BlocoX.SefazSC.BlocoXSoap)(this)).ConsultarProcessamentoArquivo(inValue);
            return retVal.Body.ConsultarProcessamentoArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarProcessamentoArquivoResponse> BlocoX.SefazSC.BlocoXSoap.ConsultarProcessamentoArquivoAsync(BlocoX.SefazSC.ConsultarProcessamentoArquivoRequest request) {
            return base.Channel.ConsultarProcessamentoArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarProcessamentoArquivoResponse> ConsultarProcessamentoArquivoAsync(string pXml) {
            BlocoX.SefazSC.ConsultarProcessamentoArquivoRequest inValue = new BlocoX.SefazSC.ConsultarProcessamentoArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.ConsultarProcessamentoArquivoRequestBody();
            inValue.Body.pXml = pXml;
            return ((BlocoX.SefazSC.BlocoXSoap)(this)).ConsultarProcessamentoArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlocoX.SefazSC.DownloadArquivoResponse BlocoX.SefazSC.BlocoXSoap.DownloadArquivo(BlocoX.SefazSC.DownloadArquivoRequest request) {
            return base.Channel.DownloadArquivo(request);
        }
        
        public string DownloadArquivo(string pXml) {
            BlocoX.SefazSC.DownloadArquivoRequest inValue = new BlocoX.SefazSC.DownloadArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.DownloadArquivoRequestBody();
            inValue.Body.pXml = pXml;
            BlocoX.SefazSC.DownloadArquivoResponse retVal = ((BlocoX.SefazSC.BlocoXSoap)(this)).DownloadArquivo(inValue);
            return retVal.Body.DownloadArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlocoX.SefazSC.DownloadArquivoResponse> BlocoX.SefazSC.BlocoXSoap.DownloadArquivoAsync(BlocoX.SefazSC.DownloadArquivoRequest request) {
            return base.Channel.DownloadArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlocoX.SefazSC.DownloadArquivoResponse> DownloadArquivoAsync(string pXml) {
            BlocoX.SefazSC.DownloadArquivoRequest inValue = new BlocoX.SefazSC.DownloadArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.DownloadArquivoRequestBody();
            inValue.Body.pXml = pXml;
            return ((BlocoX.SefazSC.BlocoXSoap)(this)).DownloadArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlocoX.SefazSC.CancelarArquivoResponse BlocoX.SefazSC.BlocoXSoap.CancelarArquivo(BlocoX.SefazSC.CancelarArquivoRequest request) {
            return base.Channel.CancelarArquivo(request);
        }
        
        public string CancelarArquivo(string pXml) {
            BlocoX.SefazSC.CancelarArquivoRequest inValue = new BlocoX.SefazSC.CancelarArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.CancelarArquivoRequestBody();
            inValue.Body.pXml = pXml;
            BlocoX.SefazSC.CancelarArquivoResponse retVal = ((BlocoX.SefazSC.BlocoXSoap)(this)).CancelarArquivo(inValue);
            return retVal.Body.CancelarArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlocoX.SefazSC.CancelarArquivoResponse> BlocoX.SefazSC.BlocoXSoap.CancelarArquivoAsync(BlocoX.SefazSC.CancelarArquivoRequest request) {
            return base.Channel.CancelarArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlocoX.SefazSC.CancelarArquivoResponse> CancelarArquivoAsync(string pXml) {
            BlocoX.SefazSC.CancelarArquivoRequest inValue = new BlocoX.SefazSC.CancelarArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.CancelarArquivoRequestBody();
            inValue.Body.pXml = pXml;
            return ((BlocoX.SefazSC.BlocoXSoap)(this)).CancelarArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlocoX.SefazSC.ReprocessarArquivoResponse BlocoX.SefazSC.BlocoXSoap.ReprocessarArquivo(BlocoX.SefazSC.ReprocessarArquivoRequest request) {
            return base.Channel.ReprocessarArquivo(request);
        }
        
        public string ReprocessarArquivo(string pXml) {
            BlocoX.SefazSC.ReprocessarArquivoRequest inValue = new BlocoX.SefazSC.ReprocessarArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.ReprocessarArquivoRequestBody();
            inValue.Body.pXml = pXml;
            BlocoX.SefazSC.ReprocessarArquivoResponse retVal = ((BlocoX.SefazSC.BlocoXSoap)(this)).ReprocessarArquivo(inValue);
            return retVal.Body.ReprocessarArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ReprocessarArquivoResponse> BlocoX.SefazSC.BlocoXSoap.ReprocessarArquivoAsync(BlocoX.SefazSC.ReprocessarArquivoRequest request) {
            return base.Channel.ReprocessarArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlocoX.SefazSC.ReprocessarArquivoResponse> ReprocessarArquivoAsync(string pXml) {
            BlocoX.SefazSC.ReprocessarArquivoRequest inValue = new BlocoX.SefazSC.ReprocessarArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.ReprocessarArquivoRequestBody();
            inValue.Body.pXml = pXml;
            return ((BlocoX.SefazSC.BlocoXSoap)(this)).ReprocessarArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfResponse BlocoX.SefazSC.BlocoXSoap.ConsultarPendenciasDesenvolvedorPafEcf(BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequest request) {
            return base.Channel.ConsultarPendenciasDesenvolvedorPafEcf(request);
        }
        
        public string ConsultarPendenciasDesenvolvedorPafEcf(string pXml) {
            BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequest inValue = new BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequest();
            inValue.Body = new BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequestBody();
            inValue.Body.pXml = pXml;
            BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfResponse retVal = ((BlocoX.SefazSC.BlocoXSoap)(this)).ConsultarPendenciasDesenvolvedorPafEcf(inValue);
            return retVal.Body.ConsultarPendenciasDesenvolvedorPafEcfResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfResponse> BlocoX.SefazSC.BlocoXSoap.ConsultarPendenciasDesenvolvedorPafEcfAsync(BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequest request) {
            return base.Channel.ConsultarPendenciasDesenvolvedorPafEcfAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfResponse> ConsultarPendenciasDesenvolvedorPafEcfAsync(string pXml) {
            BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequest inValue = new BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequest();
            inValue.Body = new BlocoX.SefazSC.ConsultarPendenciasDesenvolvedorPafEcfRequestBody();
            inValue.Body.pXml = pXml;
            return ((BlocoX.SefazSC.BlocoXSoap)(this)).ConsultarPendenciasDesenvolvedorPafEcfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlocoX.SefazSC.ConsultarPendenciasContribuinteResponse BlocoX.SefazSC.BlocoXSoap.ConsultarPendenciasContribuinte(BlocoX.SefazSC.ConsultarPendenciasContribuinteRequest request) {
            return base.Channel.ConsultarPendenciasContribuinte(request);
        }
        
        public string ConsultarPendenciasContribuinte(string pXml) {
            BlocoX.SefazSC.ConsultarPendenciasContribuinteRequest inValue = new BlocoX.SefazSC.ConsultarPendenciasContribuinteRequest();
            inValue.Body = new BlocoX.SefazSC.ConsultarPendenciasContribuinteRequestBody();
            inValue.Body.pXml = pXml;
            BlocoX.SefazSC.ConsultarPendenciasContribuinteResponse retVal = ((BlocoX.SefazSC.BlocoXSoap)(this)).ConsultarPendenciasContribuinte(inValue);
            return retVal.Body.ConsultarPendenciasContribuinteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarPendenciasContribuinteResponse> BlocoX.SefazSC.BlocoXSoap.ConsultarPendenciasContribuinteAsync(BlocoX.SefazSC.ConsultarPendenciasContribuinteRequest request) {
            return base.Channel.ConsultarPendenciasContribuinteAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarPendenciasContribuinteResponse> ConsultarPendenciasContribuinteAsync(string pXml) {
            BlocoX.SefazSC.ConsultarPendenciasContribuinteRequest inValue = new BlocoX.SefazSC.ConsultarPendenciasContribuinteRequest();
            inValue.Body = new BlocoX.SefazSC.ConsultarPendenciasContribuinteRequestBody();
            inValue.Body.pXml = pXml;
            return ((BlocoX.SefazSC.BlocoXSoap)(this)).ConsultarPendenciasContribuinteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlocoX.SefazSC.ListarArquivosResponse BlocoX.SefazSC.BlocoXSoap.ListarArquivos(BlocoX.SefazSC.ListarArquivosRequest request) {
            return base.Channel.ListarArquivos(request);
        }
        
        public string ListarArquivos(string pXml) {
            BlocoX.SefazSC.ListarArquivosRequest inValue = new BlocoX.SefazSC.ListarArquivosRequest();
            inValue.Body = new BlocoX.SefazSC.ListarArquivosRequestBody();
            inValue.Body.pXml = pXml;
            BlocoX.SefazSC.ListarArquivosResponse retVal = ((BlocoX.SefazSC.BlocoXSoap)(this)).ListarArquivos(inValue);
            return retVal.Body.ListarArquivosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ListarArquivosResponse> BlocoX.SefazSC.BlocoXSoap.ListarArquivosAsync(BlocoX.SefazSC.ListarArquivosRequest request) {
            return base.Channel.ListarArquivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlocoX.SefazSC.ListarArquivosResponse> ListarArquivosAsync(string pXml) {
            BlocoX.SefazSC.ListarArquivosRequest inValue = new BlocoX.SefazSC.ListarArquivosRequest();
            inValue.Body = new BlocoX.SefazSC.ListarArquivosRequestBody();
            inValue.Body.pXml = pXml;
            return ((BlocoX.SefazSC.BlocoXSoap)(this)).ListarArquivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlocoX.SefazSC.ConsultarHistoricoArquivoResponse BlocoX.SefazSC.BlocoXSoap.ConsultarHistoricoArquivo(BlocoX.SefazSC.ConsultarHistoricoArquivoRequest request) {
            return base.Channel.ConsultarHistoricoArquivo(request);
        }
        
        public string ConsultarHistoricoArquivo(string pXml) {
            BlocoX.SefazSC.ConsultarHistoricoArquivoRequest inValue = new BlocoX.SefazSC.ConsultarHistoricoArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.ConsultarHistoricoArquivoRequestBody();
            inValue.Body.pXml = pXml;
            BlocoX.SefazSC.ConsultarHistoricoArquivoResponse retVal = ((BlocoX.SefazSC.BlocoXSoap)(this)).ConsultarHistoricoArquivo(inValue);
            return retVal.Body.ConsultarHistoricoArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarHistoricoArquivoResponse> BlocoX.SefazSC.BlocoXSoap.ConsultarHistoricoArquivoAsync(BlocoX.SefazSC.ConsultarHistoricoArquivoRequest request) {
            return base.Channel.ConsultarHistoricoArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarHistoricoArquivoResponse> ConsultarHistoricoArquivoAsync(string pXml) {
            BlocoX.SefazSC.ConsultarHistoricoArquivoRequest inValue = new BlocoX.SefazSC.ConsultarHistoricoArquivoRequest();
            inValue.Body = new BlocoX.SefazSC.ConsultarHistoricoArquivoRequestBody();
            inValue.Body.pXml = pXml;
            return ((BlocoX.SefazSC.BlocoXSoap)(this)).ConsultarHistoricoArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlocoX.SefazSC.ConsultarStatusMetodosBlocoXResponse BlocoX.SefazSC.BlocoXSoap.ConsultarStatusMetodosBlocoX(BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequest request) {
            return base.Channel.ConsultarStatusMetodosBlocoX(request);
        }
        
        public string ConsultarStatusMetodosBlocoX() {
            BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequest inValue = new BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequest();
            inValue.Body = new BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequestBody();
            BlocoX.SefazSC.ConsultarStatusMetodosBlocoXResponse retVal = ((BlocoX.SefazSC.BlocoXSoap)(this)).ConsultarStatusMetodosBlocoX(inValue);
            return retVal.Body.ConsultarStatusMetodosBlocoXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarStatusMetodosBlocoXResponse> BlocoX.SefazSC.BlocoXSoap.ConsultarStatusMetodosBlocoXAsync(BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequest request) {
            return base.Channel.ConsultarStatusMetodosBlocoXAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlocoX.SefazSC.ConsultarStatusMetodosBlocoXResponse> ConsultarStatusMetodosBlocoXAsync() {
            BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequest inValue = new BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequest();
            inValue.Body = new BlocoX.SefazSC.ConsultarStatusMetodosBlocoXRequestBody();
            return ((BlocoX.SefazSC.BlocoXSoap)(this)).ConsultarStatusMetodosBlocoXAsync(inValue);
        }
    }
}
